agf-tests/force-app/main/default/objects/TST_VINC__c/TST_VINC__c.object-meta.xml
<CustomObject>
    <description>touchpoint</description>
    <label>VINC</label>
    <nameField>
        <displayFormat>VIN-{00000}</displayFormat>
        <label>Código VINC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VINCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agf-tests/force-app/main/default/objects/TST_VINC__c/fields/Lk_CI__c.field-meta.xml
<CustomField>
    <fullName>Lk_CI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>relacionamento CI</inlineHelpText>
    <label>CI</label>
    <referenceTo>TST_CI__c</referenceTo>
    <relationshipLabel>VINCs</relationshipLabel>
    <relationshipName>VINCs</relationshipName>
    <type>Lookup</type>
</CustomField>

agf-tests/force-app/main/default/classes/VincRecord.cls
/**
 * @description Global data class para representar um registro TST_VINC__c
 * 
 * Padrão: Global class (obrigatório para Lightning Types reconhecerem)
 * Propriedades: id, name, dates, owner, tst_ci_id (relacionamento)
 * 
 * Nota: Diferente de CiRecord, VincRecord é um "folha" - não tem aninhamento
 */
global class VincRecord {
    
    @InvocableVariable(label='ID do Registro VINC')
    global String id;
    
    @InvocableVariable(label='Nome do Registro VINC')
    global String name;
    
    @InvocableVariable(label='Data de Criação')
    global String createdDate;
    
    @InvocableVariable(label='Última Modificação')
    global String lastModifiedDate;
    
    @InvocableVariable(label='Owner ID')
    global String ownerId;
    
    @InvocableVariable(label='ID do TST_CI relacionado')
    global String lk_ci_id;
    
    
    /**
     * Constructor - Converte TST_VINC__c Sobject para VincRecord
     * 
     * Conversão importante:
     *   - Datetime → String (formato YYYY-MM-DD)
     * 
     * @param vinc Registro TST_VINC__c do banco
     */
    global VincRecord(TST_VINC__c vinc) {
        this.id = vinc.Id;
        this.name = vinc.Name;
        this.createdDate = vinc.CreatedDate != null ? 
            vinc.CreatedDate.format('yyyy-MM-dd') : '';
        this.lastModifiedDate = vinc.LastModifiedDate != null ? 
            vinc.LastModifiedDate.format('yyyy-MM-dd') : '';
        this.ownerId = vinc.OwnerId;
        this.lk_ci_id = vinc.Lk_CI__c;
    }
}